version: '3'
services:
  mongodb:
    image: 'mongo'
    environment:
      MONGO_INITDB_DATABASE: 'bahamas'
      MONGO_INITDB_ROOT_USERNAME: 'bahamasinvoice'
      MONGO_INITDB_ROOT_PASSWORD: 'bahamasinvoice'
    ports:
      - "27017:27017"
    volumes:
      -  ./mongo-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  web:
    build: .
    container_name: 'bahamas-invoice-api'
    ports:
      - "8080:8080"
